/**
 * Autogenerated symbols to indicate the version of the library.
 */
#ifndef VERSION_H
#define VERSION_H


// version string
extern const char *gVersion;
// build date
extern const char *gBuildDate;

#endif
